controller:
  replicaCount: 2
  config:
    enable-underscores-in-headers: "true"
    use-forwarded-headers: "true"
  proxySetHeaders:
    use-forwarded-headers: "true"
  service:
    type: "LoadBalancer"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      kubernetes.io/ingress.class: nginx
